[project]
name = "beeai-chat"
version = "0.1.0"
description = "Simple Chat example in BeeAI Framework"
authors = [
    {name = "Lukáš Janeček",email = "xjacka@gmail.com"}
]
readme = "README.md"
requires-python = "<4.0,>=3.11"
dependencies = [
    "beeai-framework[a2a,search] (>=0.1.36,<0.2.0)"
]
