[project]
name = "beeai-chat-client"
version = "0.1.0"
description = "Simple Chat client in BeeAI Framework for beeai-chat agent"
authors = [
    {name = "Lukáš Janeček",email = "xjacka@gmail.com"}
]
readme = "README.md"
requires-python = "<4.0,>=3.11"
dependencies = [
    "beeai-framework[a2a] (>=0.1.36,<0.2.0)",
    "pydantic (>=2.10,<3.0.0)",
]
